In [22]:
# Libraries used
import numpy as np

### Q1: (3 points)
Write a Python program to create 100 random integers and print out all the prime numbers.

In [23]:
random_arr = np.random.randint(1, 1001, 100)
print('Random array:\n', random_arr)

def is_prime(num):
    # all prime numbers are greater than 1
    if num > 1:
        for i in range(2, int(num ** 0.5) + 1):
            if num % i == 0:
                return False
        return True


prime_numbers_filtered = [int(num) for num in random_arr if is_prime(num)]
print("\nPrime numbers:", prime_numbers_filtered)


Random array:
 [ 857  511   71  673  369  216  820  913  436  721  658  184  737  211
  610  894  255  202  665  309  374  868  585   38  360  873  778  393
  330  286  507  886  701  876  716  203  161  661  661  213    6  720
  606  595  116  330  133  808  232  725  570  843  861  837  780  331
  520  309  321  344  405  167   45  586    2   94  165  668   76  149
  410  747   27  297   52  867  271   95 1000  273   16  127  249  400
  894  306  414  743  114  894  779  703 1000  156  544  507  147  790
  332  839]

Prime numbers: [857, 71, 673, 211, 701, 661, 661, 331, 167, 2, 149, 271, 127, 743, 839]


###  Q2: (3 points)
Create a NumPy array of shape (4, 3) with random integers between 1 and 50.

Write code to:
- Find the maximum value in the array.
- Calculate the mean of each row.
- Replace all values greater than 25 with 0.

In [24]:
arr = np.random.randint(1, 51, (4,3))
print(arr)

print("\nMaximum value in the array:", np.max(arr))

row_means = np.mean(arr, axis=1)
print("\nMean of each row:\n", row_means)

arr[arr > 25] = 0
print("\n Array with values > 25 replaced with 0:\n", arr)

[[43 31  5]
 [44 30 34]
 [19 27  3]
 [42 37 33]]

Maximum value in the array: 44

Mean of each row:
 [26.33333333 36.         16.33333333 37.33333333]

 Array with values > 25 replaced with 0:
 [[ 0  0  5]
 [ 0  0  0]
 [19  0  3]
 [ 0  0  0]]


### Q3: (4 points)
Write a Python program to perform the following tasks:

1. Generate a 5×6 matrix, X, with random values sampled from a normal distribution (mean = 0, standard deviation = 1).
2. Perform the following calculation for each element in X:
Y = 1 / 1+e^x
3. Save the resulting matrix Y into a new file named result.txt, ensuring the matrix is formatted for readability.

In [25]:
X = np.random.normal(0, 1, (5, 6))
print("Matrix X:\n", X)

Y = 1 / (1 + np.exp(X)) 
print("\nCalculation in Y:\n", Y)

np.savetxt("result.txt", Y, fmt="%.8f")
print("\nFile created!")

Matrix X:
 [[ 1.86100191 -1.81427862  0.17006437 -0.01828658 -0.04936766 -1.10089793]
 [ 0.5227103  -0.49088883 -1.72273022  0.16702831  0.50586845 -0.48970231]
 [ 1.2429022   0.24185661  0.42212275  0.51319095  1.51735626 -1.98196715]
 [-0.24873333 -2.24527052  0.00609162 -1.51431872  0.01918527 -0.115432  ]
 [-1.33984939 -1.50584656  0.00354272  0.56047403  1.05313586  0.62474524]]

Calculation in Y:
 [[0.13458631 0.85987819 0.45758608 0.50457152 0.51233941 0.75042831]
 [0.37221869 0.6203158  0.84848017 0.45833973 0.37616256 0.6200363 ]
 [0.22393122 0.43982887 0.39600891 0.37444579 0.17985115 0.87889071]
 [0.56186471 0.9042418  0.4984771  0.81970036 0.49520383 0.528826  ]
 [0.79246517 0.81844485 0.49911432 0.36343778 0.25862338 0.34870299]]

File created!
