My solutions

In [ ]:
import numpy as np

arr = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)
# Simulate 1,000 coin flips
# coin_flips = np.random.randint(0, 2, 1000)

print(arr)

# sum all elements
print(arr.sum())

#find the maximun and minimun elements
print(arr.max())
print(arr.min())

# replace all values greater than 5 with 0


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
9
1


In [23]:
#Q1
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)

# 1. Subtract the column mean from each element in the respective column
col_means = arr.mean(axis=0) # np.mean(arr, axis=0)
print("Col means:\n", col_means)
arr_centered = arr - col_means
print("Array after subtracting column means:\n", arr_centered)

# 2. Extract elements divisible by 3 into a 1D array
divisible_by_3 = arr[arr % 3 == 0]
print("Elements divisible by 3:", divisible_by_3)

# 3. Replace diagonal elements with 100
np.fill_diagonal(arr, 100)
print("Array with diagonal elements replaced by 100:\n", arr)

Col means:
 [4. 5. 6.]
Array after subtracting column means:
 [[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]
Elements divisible by 3: [3 6 9]
Array with diagonal elements replaced by 100:
 [[100   2   3]
 [  4 100   6]
 [  7   8 100]]


In [27]:
# Q2 Simulate 1,000 coin flips (0 = Tails, 1 = Heads)
from itertools import groupby 

coin_flips = np.random.randint(0, 2, size=1000)

# Count the number of Heads (1s) and Tails (0s)
num_heads = np.sum(coin_flips)
num_tails = len(coin_flips) - num_heads
print("Number of Heads:", num_heads)
print("Number of Tails:", num_tails)

# Determine the longest streak of Heads
# Find consecutive 1s (Heads) using np.diff
longest_heads_streak = max(
    (len(list(group)) for value, group in groupby(coin_flips) if value == 1), 
    default=0
)
print("Longest streak of Heads:", longest_heads_streak)


Number of Heads: 488
Number of Tails: 512
Longest streak of Heads: 10


Professor's solutions

In [30]:
# Tutorial
arrProf = np.random.randint(1,10, 9).reshape(3,3)
# arr = np.random.randint(1, 11, (3, 3))
print(arrProf)
print(np.sum(arrProf))
print(np.min(arrProf))
print(np.max(arrProf))
# Replace all values greater than 5 with 0
arrProf[arrProf>5]=0
print("Modified Array (values > 5 replaced with 0):\n", arrProf)

[[1 1 9]
 [7 5 2]
 [7 3 2]]
37
1
9
Modified Array (values > 5 replaced with 0):
 [[1 1 0]
 [0 5 2]
 [0 3 2]]


In [32]:
#Q2 
arrProf = np.random.randint(0,2, 1000)

heads = np.sum(arrProf)
print(heads)

print('tails:'+str(1000-heads))

current_longest = 0
longest = 0

for item in arrProf:
    if item == 1:
        current_longest+=1
        if current_longest > longest:
            longest = current_longest
        else:
            current_longest = 0

print(longest)

507
tails:493
507


In [ ]:
# Não lembro pra q serve

is_head = flips == 1
streak_lengths = np.diff(np.where(np.concatenate(([False], ~is_head, [False])))[0]) - 1
longest_streak = np.max(streak_lengths) if len(streak_lengths) > 0 else 0